on:
  workflow_call:
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true

jobs:
  build-workflow:
    runs-on: ubuntu-latest
    outputs:
      git_version: ${{ steps.gitversion.outputs.fullSemVer }}
      git_repo_name: ${{ steps.set-envs.outputs.git_repo_name }}
      docker_image_name: ${{ steps.set-envs.outputs.docker_image_name }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.9
        with:
          versionSpec: '5.6.7'
           
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.9

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set envs
        id: set-envs
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F / '{print $2}')
          echo "::set-output name=git_repo_name::${REPO_NAME}"
          PROJECT=talentfabric
          TAG=${{ steps.gitversion.outputs.fullSemVer }}
          IMAGE_NAME=${PROJECT}/${REPO_NAME}:${TAG}
          echo "::set-output name=docker_image_name::${IMAGE_NAME}"

  deploy-workflow:
    needs: build-workflow
    runs-on: ubuntu-latest
    steps:
      - name: print envs
        run: |
          REGISTRY=737852819915.dkr.ecr.us-east-1.amazonaws.com
          echo ${{needs.build-workflow.outputs.git_version}}
          echo ${{needs.build-workflow.outputs.git_repo_name}}
          echo ${REGISTRY}/${{needs.build-workflow.outputs.docker_image_name}}
  #     - name: docker build and push # split build and push steps
  #       env:
  #         REGISTRY: 737852819915.dkr.ecr.us-east-1.amazonaws.com
  #         PROJECT: talentfabric
  #         REPO: ${{ env.git_repo_name }}
  #         TAG: ${{ env.gitversion }}
  #         DOCKER_FILE: ${{ env.git_repo_name }}/Dockerfile
  #         BUILD_CONTEXT: ${{ env.git_repo_name }}
  #       run: |
  #         aws sts get-caller-identity
  #         IMAGE_NAME=${REGISTRY}/${PROJECT}/${REPO}:${TAG}
  #         echo "docker build ${IMAGE_NAME}"

  # deploy-workflow:

      # - name: commit-tag-build
      #   env:
      #     TAG: ${{ env.gitversion }}
      #   run: |
      #     git -C ${{ env.git_repo_name }} config user.name "GitHub Actions Bot"
      #     git -C ${{ env.git_repo_name }} config user.email "<>"
      #     git -C ${{ env.git_repo_name }} tag "${TAG}" || true
      #     git -C ${{ env.git_repo_name }} push --tags || true