on:
  workflow_call:
    inputs:
      username:
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/reusable-workflow.yaml
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.GH_PAT }}
